### ISSUE TITLE
bug: docker-compose  up failed

### ISSUE THREAD

**Issue by CNDrwei** [douyu/jupiter-layout#63]
![image](https://user-images.githubusercontent.com/40556785/211059639-c78b4ff0-6b40-45d2-a1c1-6226fcc08991.png)
can not create juno's tables

**Comment by hnlq715** [comment]
Thanks for your feedback, I'll look into this ASAP.

**Comment by hnlq715** [comment]
@CNDrwei fixed in #64 :-)
